apiVersion: apps/v1
kind: Deployment
metadata:
  name: K8s-deployment
  namespace: default
  labels:
    app: test-api
spec:
  selector:
    matchLabels:
      app: test-api
  replicas: 3
  template:
    metadata:
      labels:
        app: test-api 
    spec:
      containers:
      - name: node-api
        image: rosechege/sample_image:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      restartPolicy: Always
